package com.edu.untref.gcu.carga;

public enum Materias {
ANALISISMATEMATICOI(111),
FISICAI(112),
MATEMATICADISCRETAI(113),
ESTRUCTURASDEDATOSI(114),
ALGEBRAI(115),
PROBLEMASDEHISTORIADELSIGLO20(116),
TALLERDEINTRODUCCIONALAPROBLEMATICADELMUNDOCONTEMPORANEO(117),
FISICAII(121),
ANALISISMATEMATICOII(122),
MATEMATICADISCRETAII(123),
LENGUAJEDEPROGRAMACIONI(124),
ALGEBRAII(125),
CULTURACONTEMPORANEA(126),
PROBABILIDADYESTADISTICAI(211),
ANALISISMATEMATICOIII(212),
ESTRUCTURASDEDATOSII(213),
TEORIADESISTEMAS(214),
LENGUAJEDEPROGRAMACIONII(215),
CUESTIONESDESOCIOLOGIAECONOMIAYPOLITICA(216),
FISICAIII(221),
PROBABILIDADYESTADISTICAII(222),
ARQUITECTURADECOMPUTADORAS(223),
ESTRUCTURASDEDATOSIII(224),
ANALISISYDISENOESTRUCTURADO(225),
INVESTIGACIONOPERATIVA(226),
QUIMICA(311),
BASESDEDATOSI(312),
TEORIADELAINFORMACION(313),
LENGUAJEDEPROGRAMACIONIII(314),
METODOLOGIADELAINFORMACION(315),
INGLESBASICO(316),
ANALISISYDISENOORIENTADOAOBJETOS(321),
BASESDEDATOSII(322),
SISTEMASOPERATIVOS(323),
LENGUAJEDEPROGRAMACIONIV(324),
TELEINFORMATICA(325),
INGLESTECNICO(326),
ANALISISYDISENODESISTEMASENTIEMPOREAL(411),
COMPILADORESEINTERPRETES(412),
PROCESOSESTOCASTICOS(413),
INGENIERIAENSOFTWARE(414),
PROCESAMIENTODESENALESI(415),
SIMULACIONDESISTEMAS(421),
SEGURIDADINFORMATICA(422),
INTELIGENCIAARTIFICIAL(423),
PROCESAMIENTODEIMAGENES(424),
CIRCUITOSELECTRONICOS(425),
SISTEMASDEADQUISICIONDEDATOS(511),
BIOINFORMATICA(512),
ROBOTICA(513),
LABORATORIODEELECTRONICA(514),
INFORMATICAMEDICA(515),
SOFTWARELEGAL(521),
PROCESAMIENTODESENALESII(522),
AUDITORIADESISTEMAS(523),
INFORMATICAINDUSTRIAL(524),
TRABAJODETESIS(525);
	
private int codigo;

private Materias (int codigo){
	this.codigo=codigo;
}

public int getCodigo() {
	return codigo;
}

public Materias fromCodigo (int cod){
	for (Materias eachCodigo:Materias.values()){
		if (eachCodigo.equals(cod)){
			return eachCodigo;
		}
	}
	return null;
}


}
